package holaHibernate.entidades;
// Generated 20-abr-2014 19:43:10 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente" ,catalog="clientesdb" , 
        uniqueConstraints = @UniqueConstraint(columnNames="Nick") )
public class Cliente  implements java.io.Serializable {

     @Id 
     @Column(name="DNI", unique=true, nullable=false)
     private int dni;
     private String nombre;
     private String ape1;
     private String ape2;
     private String nick;
     private String passwd;
     private Float saldo;
     private Integer moroso;

    public Cliente() {
    }

	
    public Cliente(int dni, String nombre, String ape1, String nick, String passwd) {
        this.dni = dni;
        this.nombre = nombre;
        this.ape1 = ape1;
        this.nick = nick;
        this.passwd = passwd;
    }
    public Cliente(int dni, String nombre, String ape1, String ape2, String nick, String passwd, Float saldo, Integer moroso) {
       this.dni = dni;
       this.nombre = nombre;
       this.ape1 = ape1;
       this.ape2 = ape2;
       this.nick = nick;
       this.passwd = passwd;
       this.saldo = saldo;
       this.moroso = moroso;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApe1() {
        return this.ape1;
    }
    
    public void setApe1(String ape1) {
        this.ape1 = ape1;
    }
    public String getApe2() {
        return this.ape2;
    }
    
    public void setApe2(String ape2) {
        this.ape2 = ape2;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public Float getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Float saldo) {
        this.saldo = saldo;
    }
    public Integer getMoroso() {
        return this.moroso;
    }
    
    public void setMoroso(Integer moroso) {
        this.moroso = moroso;
    }




}


